-- Demo data: an invented month of household events.
--
-- Nothing here is real. It exists so that a fresh clone shows the app doing
-- its actual job (categories, the double-booking warning, standalone
-- reminders, a yearly birthday, a private event, the Popcorn-style "attended"
-- feed) instead of an empty grid, and so the screenshots in the README can be
-- regenerated by anyone.
--
--   make demo          brings the stack up and loads this file
--   make demo-reset    wipes these rows and loads them again
--
-- Safe to run only on a throwaway database: it inserts, it does not merge.
-- Categories themselves are seeded by the app at startup (see main.py's
-- SEED_CATEGORIES and the Cinema/Concert/Sports/Visitors block in lifespan),
-- so this file looks them up by name and never assumes an id. Every date
-- below is relative to now(), except the birthday, whose stored year is
-- irrelevant by design: a repeats_yearly row is always projected onto the
-- current and future years, so an old stored date never goes stale.

begin;

-- A normal month: one event per household category, spread across the next
-- few weeks, mixing owners and timed/all-day shapes.
insert into events
  (title, starts_at, ends_at, all_day, owner, location, notes,
   category_id, sticker, repeats_yearly, item_kind, private)
values
  ('Family game night',
   date_trunc('day', now()) + interval '2 days 19 hours',
   date_trunc('day', now()) + interval '2 days 21 hours',
   false, 'Both', 'Living room', 'Loser does the dishes.',
   (select id from categories where name = 'Family'), '🎲', false, 'event', false),

  ('Quarterly planning review',
   date_trunc('day', now()) + interval '4 days 10 hours',
   date_trunc('day', now()) + interval '4 days 11 hours 30 minutes',
   false, 'Willian', 'Office', '',
   (select id from categories where name = 'Work'), '💼', false, 'event', false),

  ('Dentist checkup',
   date_trunc('day', now()) + interval '6 days 9 hours',
   date_trunc('day', now()) + interval '6 days 10 hours',
   false, 'Aline', 'Downtown dental clinic', 'Bring the insurance card.',
   (select id from categories where name = 'Health'), '🦷', false, 'event', false),

  ('Movie night at home',
   date_trunc('day', now()) + interval '8 days 20 hours',
   date_trunc('day', now()) + interval '8 days 22 hours',
   false, 'Both', '', 'Pick something nobody has seen.',
   (select id from categories where name = 'Fun'), '🍿', false, 'event', false),

  -- The all-day, multi-day event: also the Travel-category row the
  -- "attended" feed (app/main.py's ATTENDED list) picks up.
  ('Weekend trip to the mountains',
   date_trunc('day', now()) + interval '12 days',
   date_trunc('day', now()) + interval '15 days',
   true, 'Both', 'Cabin rental', 'Pack the hiking boots, not the sandals.',
   (select id from categories where name = 'Travel'), '🏔️', false, 'event', false),

  -- One of each category the app feeds to its "attended" export.
  ('See the new sci-fi release',
   date_trunc('day', now()) + interval '3 days 19 hours 30 minutes',
   date_trunc('day', now()) + interval '3 days 21 hours 45 minutes',
   false, 'Both', 'The multiplex', '',
   (select id from categories where name = 'Cinema'), '🎬', false, 'event', false),

  ('Local jazz trio, downtown',
   date_trunc('day', now()) + interval '9 days 20 hours',
   date_trunc('day', now()) + interval '9 days 22 hours 30 minutes',
   false, 'Willian', 'The little club on the corner', 'Get there early, it fills up.',
   (select id from categories where name = 'Concert'), '🎸', false, 'event', false),

  ('5k fun run downtown',
   date_trunc('day', now()) + interval '17 days 8 hours',
   date_trunc('day', now()) + interval '17 days 9 hours 30 minutes',
   false, 'Aline', 'Riverside park', 'Bib pickup is the day before.',
   (select id from categories where name = 'Sports'), '🏃', false, 'event', false),

  -- Visitors is deliberately NOT in the attended set (see main.py): it keeps
  -- its reminders without ever showing up in a diary feed.
  ('Aline''s parents visiting',
   date_trunc('day', now()) + interval '20 days',
   date_trunc('day', now()) + interval '22 days',
   true, 'Both', '', 'Airport pickup Friday evening.',
   (select id from categories where name = 'Visitors'), '', false, 'event', false),

  -- A private event: kept off the other person's calendar entirely (see
  -- app/main.py's visible_to()), not merely hidden in the UI.
  ('Surprise gift shopping for Aline',
   date_trunc('day', now()) + interval '5 days 12 hours',
   date_trunc('day', now()) + interval '5 days 13 hours',
   false, 'Willian', 'The mall', 'Do not mention this one.',
   (select id from categories where name = 'Fun'), '🎁', false, 'event', true),

  -- The yearly repetition: stored once, projected onto every year at render
  -- time. The stored year is arbitrary and never needs updating.
  ('Aline''s birthday',
   '1992-08-22 00:00:00-04',
   '1992-08-23 00:00:00-04',
   true, 'Both', '', 'Cake, not pie.',
   (select id from categories where name = 'Family'), '🎂', true, 'event', false)
;

-- Standalone reminders: to-dos with a due date rather than an hour, each with
-- a lead time so the daily nag stays quiet until its window opens.
insert into events
  (title, starts_at, ends_at, all_day, owner, notes,
   category_id, item_kind, lead_days)
values
  ('Renew car registration',
   date_trunc('day', now()) + interval '10 days',
   date_trunc('day', now()) + interval '10 days' + interval '1 day',
   true, 'Willian', 'Online, takes ten minutes',
   (select id from categories where name = 'Bills'), 'reminder', 7),

  ('Pay the quarterly utility bill',
   date_trunc('day', now()) + interval '16 days',
   date_trunc('day', now()) + interval '16 days' + interval '1 day',
   true, 'Aline', 'Autopay is off on this one on purpose',
   (select id from categories where name = 'Bills'), 'reminder', 5)
;

commit;
